### ISSUE TITLE
No sketchplugin file in zip folder

### ISSUE THREAD

**Issue by meghanuno1** [zeplin/emoji-autocomplete-sketch-plugin#15]
There is no sketch plugin file forma contained in the zip folder.
<img width="1140" alt="screen shot 2018-07-18 at 3 25 36 pm" src="https://user-images.githubusercontent.com/29107565/42903145-e119a646-8a9e-11e8-8d5a-17d244b467aa.png">

**Comment by berkcebi** [comment]
Closing this one, let us know if you're still having issues!
