### ISSUE TITLE
Doesn't work in symbol overrides in Sketch 52.1

### ISSUE THREAD

**Issue by Kgangi** [zeplin/emoji-autocomplete-sketch-plugin#19]
Before the sketch 52 update this worked with symbol overrides and was a time-saver.

**Comment by yigitcanyurtsever** [comment]
Hey @Kgangi 👋 

Thanks for the report, I'll investigate this and will keep you updated.

**Comment by yigitcanyurtsever** [comment]
@Kgangi we've fixed the issue and will release an update in an hour.

**Comment by yigitcanyurtsever** [comment]
@Kgangi we've released the updated, you should be able to update it from Sketch.

**Comment by Kgangi** [comment]
wow that was fast! It works great again
