### ISSUE TITLE
Flag of France can't be found

### ISSUE THREAD

**Issue by Maikenvv** [zeplin/emoji-autocomplete-sketch-plugin#22]
Hi,

thank you for this plugin. I use it often. It really helps me in my work.

Unfortunately, I do have an issue. I can't seem to find the French Flag. I tried searching on:

- France
- French
- Tricolore

But I just can't seem to find it. When I open the Mac Emoji searcher, I can find it.

![french](https://user-images.githubusercontent.com/5713166/47207701-330a5f00-d38c-11e8-953f-ab8466b94e05.png)
![france](https://user-images.githubusercontent.com/5713166/47207702-330a5f00-d38c-11e8-842f-20976170f4ba.png)

MacOS Mojave, 10.14
Sketch 52.2

**Comment by yigitcanyurtsever** [comment]
Hey @Maikenvv 👋 

Thanks for the report! It looks like the alias for the French flag is `:fr:`. Though, you'll need to scroll a bit to see it. 

I'll try to come up with a solution so that the flag emoji will show up when you type the country's name with underscores for every country. I'll keep you updated.

**Comment by yigitcanyurtsever** [comment]
@Maikenvv I fixed the issue. I'll ping you again when we release an update.

**Comment by Maikenvv** [comment]
Thank you for fixing the issue. 👍

**Comment by yigitcanyurtsever** [comment]
Hey @Maikenvv 

It may take us a while to release the next update. I'm attaching the version including the fix in case you want to install it. 

Cheers!

[Emoji Autocomplete.sketchplugin.zip](https://github.com/zeplin/emoji-autocomplete-sketch-plugin/files/2502481/Emoji.Autocomplete.sketchplugin.zip)

**Comment by Maikenvv** [comment]
Thank you. I've installed it. 👍
