### ISSUE TITLE
Not compatible with M1 Macs

### ISSUE THREAD

**Issue by studioduda** [zeplin/emoji-autocomplete-sketch-plugin#29]
Hi, just setup my new Mac MIni and this came up:
Extension not compatible with CPU architecture.
<img width="372" alt="Screenshot Mac Mini M1" src="https://user-images.githubusercontent.com/36629548/124579201-30f3d180-de4f-11eb-91de-8c241f0237f6.png">

**Comment by custa1200** [comment]
U,m this has been outstanding for a while. Could anybody from Zeppelin comment on or fix this?

**Comment by custa1200** [comment]
Thanks for this
