### ISSUE TITLE
Emoji autocomplete when overriding text

### ISSUE THREAD

**Issue by carlotronico** [zeplin/emoji-autocomplete-sketch-plugin#8]
Here at [bob.io](https://bob.io) we've developed a design system. We think it could be interesting to be able to use the plugin in text that is overrided 

![image](https://user-images.githubusercontent.com/8196159/42517435-fea51032-845f-11e8-8892-0cacecff93bb.png)

Thanks for the plugin btw!

**Comment by berkcebi** [comment]
Agreed! We immediately felt the need for this as well. 😬

This one shouldn't be too hard to implement. To put it simply, the plugin currently listens to text view selection changes and it's just a matter of understanding which text view represents the override fields.

**Comment by yigitcanyurtsever** [comment]
Hey @carlotronico 👋 

We've released version 0.2 yesterday fixing this and #9. Just wanted to keep you updated.
