### ISSUE TITLE
Emoji autocomplete when naming pages, layers and artboards

### ISSUE THREAD

**Issue by carlotronico** [zeplin/emoji-autocomplete-sketch-plugin#9]
Here at [bob.io](https://bob.io) we usually structure our sketch pages, artboards, and layers with emojis, to make it more visually attractive and differentiable

e.g.

 
![image](https://user-images.githubusercontent.com/8196159/42517733-b3b545be-8460-11e8-81d4-7e311e919f61.png)

**Comment by berkcebi** [comment]
Thanks a lot for the suggestions @carlotronico! 🎉 

In terms of implementation, this one's pretty similar to #8. It should be possible to tackle them together.

**Comment by Robcis** [comment]
I suppose this never got implemented? Was about to make a similar suggestion.
